### ISSUE TITLE
Unable to produce pdf output

### ISSUE THREAD

**Issue by itskemo** [gwmatthews/wanikani-flashcards#1]
Hey, thank you for spending time on such a wonderful help, I was wondering why am I getting following output when trying to produce PDF cards for study:

`./makecards.sh -p a4 kanji.csv `
```
a4
sed: 1: "/3/ a\\\RLmulticolcolumns": extra characters after \ at the end of a command
sed: 1: "/3/ a\\\LRmulticolcolumns": extra characters after \ at the end of a command
Nothing to print! No all found.
```

I have even tried to generate the PDF using your supplied csv files, however the output is still the same.

Thank you,

Tom

**Comment by itskemo** [comment]
suppose to be run on Linux, not macOS. Closing.

**Comment by gwmatthews** [comment]
Ah thanks for clarifying and thanks for your interest! I was about to start troubleshooting.

**Comment by itskemo** [comment]
I will install Linux distro and give it a try, thanks again for your work!

**Comment by itskemo** [comment]
Just to let you know it went flawlessly on Linux installation. 👍
